using UnityEngine;

public class Enemy : MonoBehaviour
{
    public PlayerStats player;
    public float speed = 10f;

    public int health = 100;

    public int PriceForKill = 50;

    private Transform target;
    private int waypointIndex = 0;

    void Awake()
    {
        player = PlayerStats.instance;
    }

    void Start()
    {
        target = Waypoints.points[0];
    }

    public void TakeDamage(int amount)
    {
        health -= amount;

        if (health <= 0)
        {
            Die();
        }
    }

    void Die()
    {
        player.adjustMoney(PriceForKill);

        Destroy(gameObject);
    }

    void Update()
    {
        Vector3 dir = target.position - transform.position;
        transform.Translate(dir.normalized * speed * Time.deltaTime, Space.World);

        if (Vector3.Distance(transform.position, target.position) <= 0.4f)
        {
            GetNextWaypoint();
        }
    }

    void GetNextWaypoint()
    {
        if (waypointIndex >= Waypoints.points.Length - 1)
        {
            Destroy(gameObject);
            return;
        }

        waypointIndex++;
        target = Waypoints.points[waypointIndex];
    }
}
